export const BRANCH_STRINGS = {
  navigation: 'Проекты',
  listTitle: 'Проекты',
  listLabel: 'Список проектов',
  createAction: 'Создать проект',
  createTitle: 'Новый проект',
  renameTitle: 'Переименовать проект',
  nameLabel: 'Название проекта',
  namePlaceholder: 'Например, Спорт',
  saveAction: 'Сохранить',
  cancelAction: 'Отмена',
  searchLabel: 'Поиск проектов',
  searchPlaceholder: 'Введите часть названия',
  clearSearchAction: 'Сбросить поиск',
  loadMoreAction: 'Загрузить ещё',
  loading: 'Загружаем проекты…',
  loadingMore: 'Загружаем…',
  emptyTitle: 'Пока нет проектов',
  emptyDescription: 'Создайте первое направление, чтобы начать планировать дела.',
  noResultsTitle: 'Ничего не найдено',
  noResultsDescription: 'Попробуйте изменить запрос или сбросить поиск.',
  retryAction: 'Попробовать снова',
  detailsTitle: 'Проект',
  plansPlaceholder: 'Планы и задачи пока не добавлены',
  plansDescription: 'Они появятся здесь в следующих разделах приложения.',
  archiveAction: 'Архивировать',
  archiveDialogTitle: 'Архивировать проект?',
  archiveDialogDescription: 'Проект исчезнет из рабочего списка, но его данные сохранятся.',
  archiveConfirmAction: 'Архивировать проект',
  archiveSuccess: 'Проект архивирован',
  createdSuccess: (name: string) => `Проект «${name}» создан`,
  notFoundTitle: 'Проект не найден или недоступен',
  notFoundDescription: 'Возможно, она была архивирована или у вас нет к ней доступа.',
  backToBranchesAction: 'К списку веток',
  upstreamUnavailable: 'Сервис проектов временно недоступен. Попробуйте позже.',
  loadError: 'Не удалось загрузить проекты. Попробуйте снова.',
  saveError: 'Не удалось сохранить проект. Попробуйте снова.',
  archiveError: 'Не удалось архивировать проект. Попробуйте снова.',
  nameLengthError: 'Название должно содержать от 2 до 100 символов',
  queryLengthError: 'Поисковый запрос должен содержать не более 100 символов',
} as const;
