export const BRANCH_STRINGS = {
  navigation: 'Ветки',
  listTitle: 'Ветки',
  listLabel: 'Список веток',
  createAction: 'Создать ветку',
  createTitle: 'Новая ветка',
  renameTitle: 'Переименовать ветку',
  nameLabel: 'Название ветки',
  namePlaceholder: 'Например, Спорт',
  saveAction: 'Сохранить',
  cancelAction: 'Отмена',
  searchLabel: 'Поиск веток',
  searchPlaceholder: 'Введите часть названия',
  clearSearchAction: 'Сбросить поиск',
  loadMoreAction: 'Загрузить ещё',
  loading: 'Загружаем ветки…',
  loadingMore: 'Загружаем…',
  emptyTitle: 'Пока нет веток',
  emptyDescription: 'Создайте первое направление, чтобы начать планировать дела.',
  noResultsTitle: 'Ничего не найдено',
  noResultsDescription: 'Попробуйте изменить запрос или сбросить поиск.',
  retryAction: 'Попробовать снова',
  detailsTitle: 'Ветка',
  plansPlaceholder: 'Планы и задачи пока не добавлены',
  plansDescription: 'Они появятся здесь в следующих разделах приложения.',
  archiveAction: 'Архивировать',
  archiveDialogTitle: 'Архивировать ветку?',
  archiveDialogDescription: 'Ветка исчезнет из рабочего списка, но её данные сохранятся.',
  archiveConfirmAction: 'Архивировать ветку',
  archiveSuccess: 'Ветка архивирована',
  createdSuccess: (name: string) => `Ветка «${name}» создана`,
  notFoundTitle: 'Ветка не найдена или недоступна',
  notFoundDescription: 'Возможно, она была архивирована или у вас нет к ней доступа.',
  backToBranchesAction: 'К списку веток',
  upstreamUnavailable: 'Сервис веток временно недоступен. Попробуйте позже.',
  loadError: 'Не удалось загрузить ветки. Попробуйте снова.',
  saveError: 'Не удалось сохранить ветку. Попробуйте снова.',
  archiveError: 'Не удалось архивировать ветку. Попробуйте снова.',
  nameLengthError: 'Название должно содержать от 2 до 100 символов',
  queryLengthError: 'Поисковый запрос должен содержать не более 100 символов',
} as const;
