export const NAVIGATION_TREE_STRINGS = {
  projects: 'Проекты',
  treeLabel: 'Дерево проектов',
  loading: 'Загружаем проекты…',
  empty: 'Пока нет проектов',
  newProject: 'Новый проект',
  newChildProject: 'Новый проект',
  expandProject: (name: string) => `Раскрыть проект «${name}»`,
  collapseProject: (name: string) => `Свернуть проект «${name}»`,
  projectActions: (name: string) => `Действия для проекта «${name}»`,
  actionsLabel: 'Действия проекта',
  loadMore: 'Загрузить ещё',
  retry: 'Повторить',
  unavailable: 'Дерево проектов временно недоступно. Попробуйте позже.',
  loadError: 'Не удалось загрузить дерево проектов. Попробуйте снова.',
  depthLimit: 'Нельзя создать проект глубже 7 уровней.',
  createError: 'Не удалось создать проект. Попробуйте снова.',
  taskNode: 'Задача',
  planNode: 'План работ',
} as const;
