export const WORK_PLAN_STRINGS = {
  listTitle: 'Планы работ',
  listLabel: 'Список планов работ',
  createAction: 'Создать план',
  createTitle: 'Новый план',
  renameTitle: 'Переименовать план',
  nameLabel: 'Название плана',
  namePlaceholder: 'Например, Тренировки',
  saveAction: 'Сохранить',
  cancelAction: 'Отмена',
  searchLabel: 'Поиск планов',
  searchPlaceholder: 'Введите часть названия',
  clearSearchAction: 'Сбросить поиск',
  loadMoreAction: 'Загрузить ещё',
  loading: 'Загружаем планы…',
  loadingMore: 'Загружаем…',
  emptyTitle: 'В этом проекте пока нет планов',
  emptyDescription: 'Создайте первый план, чтобы сгруппировать будущие задачи.',
  noResultsTitle: 'Ничего не найдено',
  noResultsDescription: 'Попробуйте изменить запрос или сбросить поиск.',
  retryAction: 'Попробовать снова',
  detailsTitle: 'План работ',
  parentBranchLabel: 'Проект',
  tasksPlaceholder: 'Задачи появятся в F-6',
  tasksDescription: 'Пока вы можете изменить название плана или архивировать его.',
  archiveAction: 'Архивировать',
  archiveDialogTitle: 'Архивировать план?',
  archiveDialogDescription: 'План исчезнет из рабочего списка, но его данные сохранятся.',
  archiveConfirmAction: 'Архивировать план',
  archiveSuccess: 'План архивирован',
  createdSuccess: (name: string) => `План «${name}» создан`,
  notFoundTitle: 'План не найден или недоступен',
  notFoundDescription: 'Возможно, план или его проект были архивированы, либо у вас нет доступа.',
  backToBranchAction: 'К проекту',
  upstreamUnavailable: 'Сервис планов временно недоступен. Попробуйте позже.',
  loadError: 'Не удалось загрузить планы. Попробуйте снова.',
  saveError: 'Не удалось сохранить план. Попробуйте снова.',
  archiveError: 'Не удалось архивировать план. Попробуйте снова.',
  nameLengthError: 'Название должно содержать от 2 до 150 символов',
  queryLengthError: 'Поисковый запрос должен содержать не более 150 символов',
} as const;
